version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16-browsers
      - image: circleci/mongo:4.4
        command: mongod --replSet "rs0"
    steps:
      - run:
          name: "Install mongo shell"
          command: |
            echo "apt-key ------------------"
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
            echo "deb ------------------"
            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
            echo "apt-get update ------------------"
            sudo apt-get update --allow-unauthenticated --allow-insecure-repositories
            echo "apt-get install ------------------"
            sudo apt-get install -y mongodb-org-shell --allow-unauthenticated
      - checkout
      - run:
          name: Init mongo replica set
          command: |
            node -v
            npm -v
            mongo --version
            mongo localhost --eval "db.version()"
            mongo --eval "rs.initiate()"

#       # working setup with node:14
#       sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
#       echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
#       sudo apt-get update
#       sudo apt-get install -y mongodb-org-shell
