version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
      - image: circleci/mongo:4.4
        command: mongod --replSet "rs0"
    steps:
      - run:
          name: "Initialize Replica Set"
          command: |
            echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/main' >> /etc/apk/repositories
            echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/community' >> /etc/apk/repositories
            apk update
            apk add mongodb=3.4.4-r0
            mongo mongodb://localhost:27017 --eval "rs.initiate()"
      - checkout
      # - run:
      #     name: Init mongo replica set
      #     command: |
      #       node -v
      #       npm -v
      #       mongo --version
      #       mongo localhost --eval "db.version()"
      #       mongo --eval "rs.initiate()"
#       # working setup with node:14
#       sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
#       echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
#       sudo apt-get update
#       sudo apt-get install -y mongodb-org-shell
